conversation/urls.py
from django.urls import path
from .views import *

app_name = 'conversation'

urlpatterns = [
    path('new/<int:item_pk>/', newConversation, name='new'),
    path('', chats, name='chats'),
    path('<int:pk>/', detail, name='detail'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),
    path('store/', include('myapp.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('messages/', include('conversation.urls')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from .views import *

app_name = 'dashboard'

urlpatterns=[
    path('', index, name='index'),

]

item/urls.py
from django.urls import path
from .views import *

app_name = 'item'

urlpatterns=[
    path('<int:pk>/', detail, name='detail'),
    path('new/', new, name='new'),
    path('<int:pk>/delete/', delete, name='delete'),
    path('<int:pk>/edit/', edit, name='edit'),
    path('', browse, name='browse'),
]

myapp/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from .forms import *
urlpatterns = [
    path('', index, name='index'),
    path('signup/', signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html', authentication_form=LoginForm), name='login'),
    path('profile/', profile, name='profile'),
    path('logout/', user_logout, name='logout'),
    path('category/<int:category_id>/', items_by_category, name='items_by_category'),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    email = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Email',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

class PasswordUpdateForm(PasswordChangeForm):
    pass

myapp/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect, get_object_or_404
from item.models import *
from .forms import *
import requests

def index(request):
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()
    return render(request, 'index.html', {
        'categories': categories,
        'items': items,
    })

def signup(request):

    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        API = 'o/vyTCZYYIaI395QnNgpeg==VmVz95OtCSESNmC6'
        length = '20'
        api_url = 'https://api.api-ninjas.com/v1/passwordgenerator?length={}'.format(length)
        response = requests.get(api_url, headers={'X-Api-Key': API})
        if response.status_code==requests.codes.ok:
            password_rec = response.json()["random_password"]
        else: password_rec = ''

        form = SignupForm()
        return render(request, 'signup.html', {
            'form': form,
            'recommended': password_rec,
        })

@login_required
def profile(request):
    user_form = UserUpdateForm(instance=request.user)
    password_form = PasswordChangeForm(request.user)

    if request.method == 'POST':
        if 'user_form' in request.POST:
            user_form = UserUpdateForm(request.POST, instance=request.user)
            if user_form.is_valid():
                user_form.save()
        elif 'password_form' in request.POST:
            password_form = PasswordChangeForm(request.user, request.POST)
            if password_form.is_valid():
                password_form.save()

    return render(request, 'profile.html', {'user_form': user_form, 'password_form': password_form})

def user_logout(request):
    logout(request)
    return redirect('login')

def items_by_category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    items = Item.objects.filter(category=category, is_sold=False)
    categories = Category.objects.all()

    return render(request, 'index.html', {
        'categories': categories,
        'items': items,
    })

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title> {% block title %} {% endblock %}Armarket</title>

</head>
<body>
    <nav class ="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="{% url 'index' %}" class="text-xl font-semibold">Armarket</a>

        <div class="space-x-6">
            {% if request.user.is_authenticated %}
                <a href="{% url 'item:browse' %}" class="px-6 py-3 text-lg font-semibold bg-sky-500 text-white rounded-lg hover:bg-sky-700">Browse </a>
                <a href="{% url 'profile' %}" class="px-6 py-3 text-lg font-semibold bg-sky-500 text-white rounded-lg hover:bg-sky-700">Profile</a>
                <a href="{% url 'item:new' %}" class="px-6 py-3 text-lg font-semibold bg-sky-500 text-white rounded-lg hover:bg-sky-700">Add Item</a>
                <a href="{% url 'conversation:chats' %}" class="px-6 py-3 text-lg font-semibold bg-sky-500 text-white rounded-lg hover:bg-sky-700">Chats</a>
                <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-sky-500 text-white rounded-lg hover:bg-sky-700">Dashboard</a>
                <a href="{% url 'logout' %}" class="px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-lg hover:bg-red-700">Log Out</a>
            {% else %}
                <a href="{% url 'signup' %}" class="px-6 py-3 text-lg font-semibold bg-sky-500 text-white rounded-lg hover:bg-sky-700">Sign Up</a>
                <a href="{% url 'login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-lg hover:bg-gray-700">Log In</a>
            {% endif %}
        </div>
    </nav>
    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>

   <footer class="bg-sky-700 py-4 text-white">
    <div class="container mx-auto flex justify-between">
        <div class="w-2/3 pr-10">
            <h3 class="text-xl font-semibold mb-3 text-white">About Us</h3>
            <p class="text-gray-400 leading-relaxed">
                пока не придумал
            </p>
        </div>

        <div class="w-1/3">
            <h3 class="text-xl font-semibold mb-3 text-white">Quick Links</h3>
            <ul class="space-y-2">
                <li><a href="{% url 'index' %}" class="text-white hover:text-blue-400">Home</a></li>
                <li><a href="{% url 'profile' %}" class="text-white hover:text-blue-400">Check your profile</a></li>
            </ul>
        </div>
    </div>
    <hr class="border-t border-blue-800 mt-8">
    <div class="container mx-auto mt-4 text-center text-gray-400">
        <p>&copy; 2023</p>
    </div>
</footer>
</body>
</html>

myapp/templates/index.html
{% extends 'base.html' %}
{% block title %} Welcome︱{% endblock %}
{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded xl">
        <h2 class="mb-2 text-2xl text-center"> Look for items here! </h2>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
            <h2 class="mb-12 text-2xl text-center">Categories</h2>
            <div class="grid grid-cols-3 gap-3">
                {% for category in categories %}
                     <div>
                        <a href="{% url 'items_by_category' category.id %}">
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl"> {{ category.name }}</h2>
                                <p class="text-gray-500">{{ category.items.count }} items</p>
                            </div>
                        </a>
                    </div>

                {% endfor %}
            </div>
        </div>

    <div class="grid grid-cols-3 gap-3">
        {% for item in items %}
            <div>
                 <a href="{% url 'item:detail' item.id %}">
                     <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                     </div>

                     <div class="p-y bg-white rounded-b-xl">
                            <h2 class="text-2xl"> {{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>

                     </div>
                 </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

myapp/templates/login.html
{% extends 'base.html' %}
{%block title %}Sign Up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-200 rounded-lg">
  <h1 class="mb-6 text-3xl">Log In</h1>
  <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>


    {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-lg">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

    <button class="py-4 px-8 text-lg bg-sky-700 hover:bg-sky-500 rounded-lg text-white"> Submit </button>
  </form>
</div>
{% endblock %}

myapp/templates/profile.html
{% extends 'base.html' %}
{% block title %}Profile - {% endblock %}

{% block content %}
    <h1 class="text-2xl font-semibold mb-4">Profile</h1>
    <form method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        <button type="submit" name="user_form" class="px-4 py-2 bg-sky-500 hover:bg-sky-700 text-white rounded">Save Changes</button>
    </form>

    <h2 class="text-xl font-semibold mt-4 mb-2">Change Password</h2>
    <form method="post">
        {% csrf_token %}
        {{ password_form.as_p }}
        <button type="submit" name="password_form" class="px-4 py-2 bg-sky-500 hover:bg-sky-700 text-white rounded">Change Password</button>
    </form>
{% endblock %}

myapp/templates/signup.html
{% extends 'base.html' %}
{%block title %}Sign Up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-200 rounded-lg">
  <h1 class="mb-6 text-3xl">Sign Up</h1>
  <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">You can also use our generated password:</label><br>

             <input class="w-full py-4 px-6 rounded-xl" value="{{ recommended }}">

        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Confirm password</label><br>
            {{ form.password2 }}
        </div>

    {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-lg">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

    <button class="py-4 px-8 text-lg bg-sky-500 hover:bg-sky-700 rounded-lg text-white"> Submit </button>
  </form>
</div>
{% endblock %}