conversation/urls.py
from django.urls import path
from .views import *

app_name = 'conversation'

urlpatterns = [
    path('new/<int:item_pk>/', newConversation, name='new'),
    path('', chats, name='chats'),
    path('<int:pk>/', detail, name='detail'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),
    path('store/', include('myapp.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('messages/', include('conversation.urls')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path
from .views import *

app_name = 'item'

urlpatterns=[
    path('<int:pk>/', detail, name='detail'),
    path('new/', new, name='new'),
    path('<int:pk>/delete/', delete, name='delete'),
    path('<int:pk>/edit/', edit, name='edit'),
    path('', browse, name='browse'),
]

item/models.py
from django.contrib.auth.models import User
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=255)
    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'


    def __str__(self):
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Items'

    def __str__(self):
        return self.name

class Review(models.Model):
    item = models.ForeignKey(Item, related_name='reviews', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='reviews', on_delete=models.CASCADE)
    text = models.TextField()
    rating = models.PositiveIntegerField(choices=[(i, i) for i in range(1, 6)])
    created_at = models.DateTimeField(auto_now_add=True)
    replies = models.ManyToManyField('Reply')

class Reply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

item/forms.py
from django import forms
from .models import *

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price','image',)
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'discount': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text', 'rating']
        widgets = {
            'text': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['text']
        widgets = {
            'text': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.contrib.auth.decorators import login_required
from .forms import *
from django.db.models import Q
from django.urls import reverse_lazy

def browse(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'browse.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
    })


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    if request.method == 'POST':
        Reviewform = ReviewForm(request.POST)
        Replyform = ReplyForm(request.POST)

        if Reviewform.is_valid():
            review = Reviewform.save(commit=False)
            review.item = item
            review.user = request.user
            review.save()
            return redirect('item:detail', pk=pk)
        if Replyform.is_valid():
            review = Review.objects.get(id=request.POST.get('review_id'))
            reply = Replyform.save(commit=False)
            reply.user = request.user
            reply.save()
            review.replies.add(reply)
            review.save()
            return redirect('item:detail', pk=pk)
        return redirect('item:detail', pk=pk)
    else:
        Reviewform = ReviewForm()
        Replyform = ReplyForm()

        return render(request, 'detail.html', {
            'item': item,
            'related_items': related_items,
            'review_form': Reviewform,
            'reply_form': Replyform,
        })


@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'form.html', {
        'form': form,
        'title': 'New item',
    })


@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'form.html', {
        'form': form,
        'title': 'Edit item',
    })


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

item/templates/browse.html
{% extends 'base.html' %}}

{% block title %} Browse {% endblock %}
{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form method="get" action="{% url 'item:browse' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Find a laptop, bike or car...">

                <button class="mt-2 py-4 px-8 text-lg bg-sky-500 text-white  rounded-xl">Search</button>
            </form>
            <hr class="my-6">
            <p class="font-semibold">Categories</p>
            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200{% endif %}">
                        <a href="{% url 'item:browse' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>

             <hr class="my-6">

            <ul>
                <li><a href="{% url 'item:browse' %}" class="mt-2 py-4 px-8 inline-block bg-red-500 text-lg rounded-xl text-white">Clear filters</a>
            </ul>
        </div>

        <div class="col-span-3">
              <div class="grid grid-cols-3 gap-3">
                {% for item in items %}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            <div>
                                <img src="{{ item.image.url }}" class="rounded-t-xl">
                            </div>

                            <div class="p-y bg-white rounded-b-xl">
                                <h2 class="text-2xl"> {{ item.name }}</h2>
                                <p class="text-gray-500">Price: {{ item.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
              </div>
        </div>
    </div>
{% endblock %}

item/templates/detail.html
{% extends 'base.html' %}

{% block title %} {{ item.name }} {% endblock %}

{% block content %}
    <div class="grid grid-cols-5 gap-6">
      <div class="col-span-3">
          <img src="{{ item.image.url }}" class="rounded-xl" >
      </div>
      <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl ">{{ item.name }}</h1>
        <p class="text-gray-500"><strong>Price: </strong> {{item.price}} </p>
        <p class="text-gray-500"><strong>Seller: </strong> {{item.created_by.username}} </p>
         {% if item.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Description:</strong><br>
                {{ item.description }}
            </p>
        {% endif %}
          {% if request.user == item.created_by %}
            <div class="mt-6 p-6 bg-white rounded -xl">
                <p>This is your item!</p>
                <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-sky-500 text-white rounded-xl">Edit</a>
                <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>

            </div>
        {% else %}
            <a href="{% url 'conversation:new' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-sky-500 text-white rounded-xl hover:bg-sky-700">Contact seller</a>
        {% endif %}
      </div>
    </div>
    <div class="mt-6 p-6 bg-white rounded-xl">
        <h2 class="mb-4 text-xl">Leave a Review</h2>
        <form method="post" class="mb-6">
            {% csrf_token %}
            {{ review_form.as_p }}
            <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded">Submit Review</button>
        </form>

        <h2 class="mb-4 text-xl">Reviews</h2>
        <ul>
            {% for review in item.reviews.all %}
                <li class="bg-white p-4 rounded shadow-md">
                    <div class="flex justify-between">
                        <div class="font-semibold">{{ review.user.username }}</div>
                        <div class="text-gray-500">{{ review.created_at}}</div>

                    </div>
                    <div class="ml-2 text-gray-600">{{ review.rating }}/5</div>
                    <p class="mt-2">{{ review.text }}</p>

                    <ul>
                        {% for reply in review.replies.all %}
                            <li class="reply-container ml-6">
                                <div class="reply-info ml-6">
                                    <div class="font-semibold">{{ reply.user.username }}</div>
                                    <div class="text-gray-500">{{ reply.created_at }}</div>
                                </div>
                                <div class="reply-text ml-6">
                                    <p class="mt-2">{{ reply.text }}</p>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                    <form method="post" class="mb-6 ml-12 border-l-2 pl-4 bg-gray-100 py-2">
                        <div class="mb-2">
                            <strong>Reply to this review:</strong>
                        </div>
                        {% csrf_token %}
                        <input type="hidden" value="{{ review.id }}" name="review_id">
                        {{ reply_form.as_p }}
                        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded">Submit Reply</button>
                    </form>
                </li>
            {% empty %}
                <li>No reviews yet.</li>
            {% endfor %}
        </ul>

    </div>

     <div class="mt-6 px-6 py-12 bg-gray-100 rounded xl">
        <h2 class="mb-12 text-2xl text-center"> Related items </h2>
        <div class="grid grid-cols-3 gap-3">
            {% for item in related_items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-y bg-white rounded-b-xl">
                            <h2 class="text-2xl"> {{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}

item/templates/form.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl">{{ title }}</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        <div class="space-y-4">
            {{ form.as_p  }}
        </div>
        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-lg">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-sky-700 hover:bg-sky-500 rounded-lg text-white"> Submit </button>
    </form>

{% endblock %}